modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "example"
version = "${version}"
displayName = "example"
authors = "Progames723"
description = '''

'''
#logoFile = ""

[[dependencies.example]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
